CREATE DATABASE pagination_primer;

USE pagination_primer;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    location VARCHAR(255)
);

-- dummy values
INSERT INTO users(username, email, location)
VALUES
    ('lancelot','lancelot@gmail.com','nairobi'),
    ('perceival','perceival@gmail.com','nakuru'),
    ('morgana','morgana@gmail.com','eldoret'),
    ('arthur','arthur@gmail.com','mombasa'),
    ('guinevere','guinevere@gmail.com','kisumu'),
    ('gawain','gawain@gmail.com','nyeri'),
    ('tristan','tristan@gmail.com','thika'),
    ('galahad','galahad@gmail.com','machakos'),
    ('merlin','merlin@gmail.com','kitale'),
    ('elaine','elaine@gmail.com','malindi'),
    ('kay','kay@gmail.com','kericho'),
    ('leon','leon@gmail.com','embu'),
    ('vivian','vivian@gmail.com','kakamega'),
    ('mordred','mordred@gmail.com','narok'),
    ('isolde','isolde@gmail.com','bungoma'),
    ('uther','uther@gmail.com','nyahururu'),
    ('agravaine','agravaine@gmail.com','kisii'),
    ('lot','lot@gmail.com','lodwar'),
    ('igraine','igraine@gmail.com','lamu'),
    ('pelleas','pelleas@gmail.com','homabay'),
    ('gareth','gareth@gmail.com','nyamira'),
    ('palamedes','palamedes@gmail.com','kitui'),
    ('yvaine','yvaine@gmail.com','marsabit'),
    ('niniane','niniane@gmail.com','makueni'),
    ('dagonet','dagonet@gmail.com','kilifi'),
    ('bedivere','bedivere@gmail.com','busia'),
    ('bors','bors@gmail.com','garissa'),
    ('blanchefleur','blanchefleur@gmail.com','isiolo'),
    ('balin','balin@gmail.com','meru'),
    ('balan','balan@gmail.com','murang’a'),
    ('meliodas','meliodas@gmail.com','voi'),
    ('geraint','geraint@gmail.com','wajir'),
    ('leodegrance','leodegrance@gmail.com','nanyuki'),
    ('brangaine','brangaine@gmail.com','naivasha'),
    ('lugh','lugh@gmail.com','kajiado'),
    ('cador','cador@gmail.com','embu'),
    ('tristram','tristram@gmail.com','nakuru'),
    ('ector','ector@gmail.com','nairobi'),
    ('tom','tom@gmail.com','kilgoris'),
    ('elspeth','elspeth@gmail.com','rumuruti'),
    ('liam','liam@gmail.com','webuye'),
    ('sorcha','sorcha@gmail.com','tharaka'),
    ('aeron','aeron@gmail.com','kibwezi'),
    ('cerys','cerys@gmail.com','kapenguria'),
    ('ronan','ronan@gmail.com','kitengela'),
    ('nevan','nevan@gmail.com','eldama ravine'),
    ('fianna','fianna@gmail.com','nandi hills'),
    ('rowan','rowan@gmail.com','kapsabet'),
    ('selene','selene@gmail.com','karatina'),
    ('orin','orin@gmail.com','mwea'),
    ('brendan','brendan@gmail.com','kirinyaga'),
    ('niamh','niamh@gmail.com','makindu'),
    ('cian','cian@gmail.com','kibwezi'),
    ('aoife','aoife@gmail.com','chuka'),
    ('finn','finn@gmail.com','vanga'),
    ('maeve','maeve@gmail.com','siaya'),
    ('eira','eira@gmail.com','bomet'),
    ('osian','osian@gmail.com','litein'),
    ('saoirse','saoirse@gmail.com','mtito andei'),
    ('eoin','eoin@gmail.com','wote'),
    ('aidan','aidan@gmail.com','nyamira'),
    ('sinead','sinead@gmail.com','narumoru'),
    ('conall','conall@gmail.com','maralal'),
    ('rhiannon','rhiannon@gmail.com','kibra'),
    ('dara','dara@gmail.com','gilgil'),
    ('meabh','meabh@gmail.com','moyale'),
    ('eamon','eamon@gmail.com','kapcherop'),
    ('taliesin','taliesin@gmail.com','lodwar'),
    ('orla','orla@gmail.com','bungoma'),
    ('tadhg','tadhg@gmail.com','kapsowar'),
    ('nuala','nuala@gmail.com','embu'),
    ('ronya','ronya@gmail.com','ruiru'),
    ('lile','lile@gmail.com','nyali'),
    ('cormac','cormac@gmail.com','limuru'),
    ('rosheen','rosheen@gmail.com','karuri'),
    ('eithne','eithne@gmail.com','malava'),
    ('keelan','keelan@gmail.com','luanda'),
    ('sile','sile@gmail.com','ngong'),
    ('padraig','padraig@gmail.com','kiambu'),
    ('branna','branna@gmail.com','migori'),
    ('keira','keira@gmail.com','taveta'),
    ('torin','torin@gmail.com','githurai'),
    ('dallan','dallan@gmail.com','gikambura'),
    ('aine','aine@gmail.com','karuri'),
    ('callum','callum@gmail.com','uthiru'),
    ('morna','morna@gmail.com','thindigua'),
    ('fergal','fergal@gmail.com','wangige'),
    ('iona','iona@gmail.com','kamulu'),
    ('cassian','cassian@gmail.com','ongata rongai'),
    ('nerys','nerys@gmail.com','tala'),
    ('sean','sean@gmail.com','kamukunji'),
    ('ciara','ciara@gmail.com','lang’ata'),
    ('rowena','rowena@gmail.com','dagoretti'),
    ('art','art@gmail.com','parklands'),
    ('blodwen','blodwen@gmail.com','westlands'),
    ('gruffydd','gruffydd@gmail.com','karen'),
    ('idris','idris@gmail.com','ridgeways'),
    ('lowri','lowri@gmail.com','eastleigh'),
    ('madoc','madoc@gmail.com','donholm'),
    ('taran','taran@gmail.com','pipeline'),
    ('anwen','anwen@gmail.com','komarock'),
    ('dewi','dewi@gmail.com','kayole'),
    ('elis','elis@gmail.com','buruburu'),
    ('glyn','glyn@gmail.com','lavington'),
    ('mererid','mererid@gmail.com','kilimani'),
    ('owain','owain@gmail.com','rongai'),
    ('tegwen','tegwen@gmail.com','mlolongo'),
    ('vaughan','vaughan@gmail.com','syokimau'),
    ('bryn','bryn@gmail.com','thika road'),
    ('ceridwen','ceridwen@gmail.com','makongeni'),
    ('gareth2','gareth2@gmail.com','kangundo'),
    ('tegid','tegid@gmail.com','kitengela'),
    ('deryn','deryn@gmail.com','kamiti'),
    ('emrys','emrys@gmail.com','juja'),
    ('gwen','gwen@gmail.com','chogoria'),
    ('idwal','idwal@gmail.com','karatina'),
    ('meirion','meirion@gmail.com','kieni'),
    ('teleri','teleri@gmail.com','gikambura'),
    ('wynn','wynn@gmail.com','kuresoi'),
    ('ysfael','ysfael@gmail.com','kerugoya'),
    ('zenon','zenon@gmail.com','naro moru'),
    ('elain','elain@gmail.com','moyale'),
    ('howel','howel@gmail.com','lamu'),
    ('delwyn','delwyn@gmail.com','nyandarua'),
    ('eilir','eilir@gmail.com','kitale'),
    ('glenys','glenys@gmail.com','kisumu west'),
    ('iorwerth','iorwerth@gmail.com','kisumu east'),
    ('mabyn','mabyn@gmail.com','kisumu central'),
    ('peredur','peredur@gmail.com','mbagathi'),
    ('rhian','rhian@gmail.com','mathare'),
    ('selwyn','selwyn@gmail.com','huruma'),
    ('talwyn','talwyn@gmail.com','kawangware'),
    ('ysadora','ysadora@gmail.com','kiserian'),
    ('mairon','mairon@gmail.com','ruaka'),
    ('aeron2','aeron2@gmail.com','uthiru'),
    ('nimue','nimue@gmail.com','meru'),
    ('lyonesse','lyonesse@gmail.com','embu west'),
    ('maelon','maelon@gmail.com','embu east'),
    ('rhydderch','rhydderch@gmail.com','makindu'),
    ('sion','sion@gmail.com','sotik'),
    ('tanwen','tanwen@gmail.com','keroka'),
    ('urien','urien@gmail.com','kisii'),
    ('vortimer','vortimer@gmail.com','gilgil'),
    ('wyll','wyll@gmail.com','muhoroni'),
    ('xandra','xandra@gmail.com','ol kalou'),
    ('yorath','yorath@gmail.com','njoro'),
    ('zelda','zelda@gmail.com','kimilili'),
    ('zenith','zenith@gmail.com','cheptais'),
    ('zephyr','zephyr@gmail.com','kapkatet');
